name: colcon build & test

on:
  push:
    branches:
      - jazzy
  pull_request:
    branches:
      - jazzy
  workflow_dispatch:

env:
  ROS_DISTRO: jazzy

# Cancel previously running PR jobs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  compile_and_test:
    name: Compile and test
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04
    steps:
    - uses: actions/checkout@v3
    - uses: ros-tooling/setup-ros@v0.7
    - uses: ros-tooling/action-ros-ci@v0.3
      id: action_ros_ci_step
      with:
        package-name: andino_base andino_bringup andino_control andino_description andino_firmware andino_hardware andino_slam andino_navigation
        target-ros2-distro: ${{ env.ROS_DISTRO }}
        import-token: ${{ secrets.GITHUB_TOKEN }}
